tizmagik/react-head

.babelrc, .gitignore, .size-snapshot.json, package-lock.json, package.json, rollup.config.js
In this diff I added rollup to bundle cjs and esm. With flat bundles we
can easier to control the size user consumes.
size snapshot plugin allows to track that size with every commit.
Moreover it shows treeshakability of the lib for esm bundle.
It can be less critical for user bundle but make sense when the lib is
used by another one with a set of components. So one unused component
depending on this lib will not keep this dependency in user bundle.
=> Bundle cjs and esm with rollup

.babelrc.js, .size-snapshot.json, package-lock.json, package.json
In this diff I added babel plugin which wraps propTypes with
`process.env.NODE_ENV !== 'production'` condition. This allows
webpack in production mode or rollup with replace plugin to eliminate
prop types from final bundle.
These conditions slightly increases library size but as you can see
treeshaked size (in user bundle) become smaller.
=> Remove prop-types in production

.babelrc.js, .size-snapshot.json, README.md, package-lock.json, package.json, src/HeadCollector.js, src/HeadTag.js, src/__tests__/HeadCollector.test.js, src/headTagsContext.js
New context api eliminates static context types fields. This allows
uglify/terser to remove unused HeadCollector class from user bundle.
Having HeadCollector still is not required. Stub implementation is
provided as context default.
This PR introduces a breaking change with new context api.
Now react 16.3 or greater version is required.
=> Migrate to new react context api

.size-snapshot.json, README.md, src/HeadTag.js, src/__tests__/HeadCollector.test.js, src/__tests__/HeadTags.node.test.js, src/__tests__/HeadTags.web.test.js, src/index.js
Since we had `<Meta />` alias I think we don't need `<HeadTag />` default tag
as `meta`. It's better to keep it required. This allows us to get rid
from `defaultProps` static property and slightly improve the size of
bundle.
Default and named exports in one module often lead to broken esm/cjs interop.
Using only named exports solves the problem.
```
-import HeadTag from 'react-head';
+import { HeadTag } from 'react-head';
- <HeadTag charset='utf-8' />
+ <HeadTag tag='metameta' charset='utf-8' />
```
=> Remove HeadTag defaults and get rid from default export

.size-snapshot.json, README.md, src/HeadCollector.js, src/HeadTag.js, src/__tests__/HeadCollector.test.js, src/__tests__/HeadTags.node.test.js, src/__tests__/HeadTags.web.test.js, src/headTagsContext.js, src/index.js
In this diff I change default and mixed react imports to named only.
From discussion with Dan Abramov I have a readmap for esm in react.
In react v17 there will be esm entry point with both named and default
export but docs and all components will be recommended to migrate
to named exports. I moving this initiative forward in a lot of modules.
Size also became slightly smaller because of simpler cjs interop.
=> Prefer react named exports

.size-snapshot.json, package-lock.json, package.json, rollup.config.js
After discussion in https://github.com/tizmagik/react-head/pull/26
I decided to removed polyfills from babel since they all covers only
es5. This trimmed final bundle size significantly from 5kb gzipped to
1kb.
To track this I provided umd bundle in size snapshot.
=> Provide umd bundle and prefer builtins in helpers

.eslintrc.js, .size-snapshot.json, package-lock.json, package.json, src/HeadTag.js, src/__tests__/HeadProvider.test.js, src/__tests__/HeadTags.node.test.js, src/__tests__/HeadTags.web.test.js, utils/setup.js
enzyme maintainer doesn't want to release new react features partially
so we stuck with lack of features. `react-test-renderer` is a thin
alternative officially supported by react team. So it's a better choice
here.
=> Replace enzyme with react-test-renderer

.size-snapshot.json, README.md, package-lock.json, src/__tests__/HeadProvider.test.js, src/__tests__/HeadTags.node.test.js, src/__tests__/HeadTags.web.test.js, src/__tests__/__snapshots__/HeadProvider.test.js.snap, src/__tests__/__snapshots__/HeadTags.node.test.js.snap, src/__tests__/__snapshots__/HeadTags.web.test.js.snap, src/index.js, src/index.js.flow, src/test_flow.js
Ref https://github.com/tizmagik/react-head/issues/41
We provider all of the W3C-compliant head tags, so HeadTag is not
necessary as public api anymore.
=> Remove HeadTag in favor of head tag components

.babelrc.js, .eslintrc.js, .size-snapshot.json, package-lock.json, package.json, rollup.config.js, src/HeadProvider.js, src/__tests__/HeadTags.node.test.js, src/__tests__/HeadTags.web.test.js
Ref https://github.com/tizmagik/react-head/issues/41
In this diff I made headTags optional and call invariant with ssr
check.
For invariant I used `tiny-invariant` package which is quite small and
simplified version of `fbjs/lib/invariant`.
`babel-plugin-dev-expression` wraps invariant with two cases
- throw error with message in development
- throw empty error in production `invariant failed` message
This allows to strip development only messages and save bytes in user
bundle.
=> Make headTags in <HeadProvider /> optional for client

.babelrc.js, .size-snapshot.json, package-lock.json, package.json, src/HeadProvider.js, src/HeadTag.js, tests/ssr.test.js
`HeadTag` is implementation detail and aliases always pass tag prop,
prop-types are not required in this component.
`HeadProvider` prop types are not significant. `headTags` is asserted
in render. Covering `children` doesn't have any DX matter.
=> Remove prop-types

README.md, example/README.md, example/package-lock.json, example/package.json, example/src/App.js, example/src/App.test.js, example/src/Contact.js, example/src/Home.js, example/src/client.js, example/src/index.js, example/src/server.js, package.json
=> Update Example for v3 API

.size-snapshot.json, src/HeadProvider.js
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) the `NodeList` returned by `querySelectorAll` only supports `forEach` in modern browsers. The most notable browser missing off this list if Chromium ~41, which is the rendering ending that Googlebot is based on. By removing the `NodeList` `forEach` call, also per the MDN article, we can get Google rendering again.
=> Allow Googlebot and older browsers to render HeadProvider

.size-snapshot.json, src/HeadProvider.js
This prevents an exception in IE because ChildNode.remove() is not supported there.
=> ssrTags are removed using removeSafe method

src/index.js.flow
I know who uses flow anymore right?
=> Flow doesn't like passing no type parameter to React.Element, so pass `any`

package.json, src/index.d.ts
Fixes #75
As src folder is still published due to dist flow types referral, I just added reference to `src/index.d.ts` and didn't touch any build scripts for now.
=> Add Typescript typings

src/index.d.ts
```ts
import { Link } from 'react-head';
...
<Link
rel="stylesheet"
href="//cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css"
/>
```
I was using the `Link` component and was receiving this error:
```
Property 'rel' does not exist on type 'IntrinsicAttributes & HTMLAttributes<HTMLLinkElement> & { children?: ReactNode; }'
```
I took a look on the typings and I realized that they were using the generic `HTMLAttributes` interface rather than the more specific for each tag that includes the particularities of each one, so I went ahead and changed it, and the errors were gone.
cc @TrySound @msokk as per #78.
=> fix(typings): fix type definitions for exported HTML components

.size-snapshot.json, babel.config.js, package-lock.json, package.json, src/HeadProvider.js, src/HeadTag.js, tests/ReactDOMMock.js
I used invariant and warning packages a lot lately. And after coming back
to the code with them I found myself confused on which codition
invariant/warning is happened.
I suggest to use explicit conditions and simple throw Error inside.
=> Drop tiny-invariant

.size-snapshot.json, package-lock.json, package.json, rollup.config.js
Official rollup plugins are migrated to scoped packages. Also replaced
uglify with terser (which is a fork of abandoned uglify-es).
=> Upgrade rollup

.size-snapshot.json, README.md, example/src/Home.js, src/index.d.ts, src/index.js, src/index.js.flow, src/test_flow.js, tests/__snapshots__/dom.test.js.snap, tests/__snapshots__/ssr.test.js.snap, tests/__snapshots__/web.test.js.snap, tests/dom.test.js, tests/ssr.test.js, tests/web.test.js
I'm in a similar situation as @maparent in https://github.com/tizmagik/react-head/issues/102. Managing a `<base>` tag would be useful when when situating an app within a dynamic path. I also considered exposing the `HeadTag` component directly, but according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#See_also), the only head tags not currently supported are `<base>`, `<script>`, `<noscript>`, and `<template>`, and if you're trying to use react to manage `<script>`, `<noscript>` , or `<template>` tags, you've probably got bigger issues.
So here's a PR that exposes `<base>` tags as a `<Base>` component, complete with documentation, example, and typings.
=> Expose component for <base> tag

src/index.d.ts
This issue breaks apps with React 18. Fixes #140
=> Add explicit `children` prop to `HeadProvider`
